version: "3.9"
services:
  backend:
    image: backend
    build:
      context: ./backend
      args:
        - target=dev
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: ${MYSQL_HOST}
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: "Asia/Tokyo"
    volumes:
      - $PWD/backend/_tools/mysql/initdb.d:/docker-entrypoint-initdb.d
      - $PWD/backend/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
      - "${MYSQL_PORT}:3306"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
