version: "3.9"
services:
  backend:
    image: backend
    build:
      context: ./backend
      args:
        - target=dev
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
  db:
    image: mysql:latest
    depends_on:
      - backend
    container_name: todo-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - $PWD/backend/_tools/mysql/initdb.d:/docker-entrypoint-initdb.d
      - $PWD/backend/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
      - "3306:3306"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
volumes:
  db-data:
