version: "3.9"
services:
  backend:
    image: backend
    build:
      context: ./backend
      args:
        - target=dev
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

